### ISSUE TITLE
Cannot compile on CentOS 7 with GCC 13.2

### ISSUE THREAD

**Issue by runiq** [breuner/elbencho#66]
I'm trying to compile elbencho on an older HPC cluster running CentOS 7, GCC 13.2.0, and CUDA 11.0 without Cufile support. I'm getting this error:

```
$ make
[...]
source/ProgArgs.cpp: In member function 'void ProgArgs::parseGPUIDs()':
source/ProgArgs.cpp:2145:25: error: 'cudaError_t' was not declared in this scope
 2145 |                         cudaError_t getDevsRes = cudaGetDeviceCount(&numCudaDevs);
      |                         ^~~~~~~~~~~
source/ProgArgs.cpp:2147:28: error: 'getDevsRes' was not declared in this scope; did you mean 'netDevsVec'?
 2147 |                         if(getDevsRes != cudaSuccess)
      |                            ^~~~~~~~~~
      |                            netDevsVec
source/ProgArgs.cpp:2147:42: error: 'cudaSuccess' was not declared in this scope
 2147 |                         if(getDevsRes != cudaSuccess)
      |                                          ^~~~~~~~~~~
source/ProgArgs.cpp:2149:58: error: 'cudaGetErrorString' was not declared in this scope
 2149 |                                         "CUDA Error: " + cudaGetErrorString(getDevsRes) );
      |                                                          ^~~~~~~~~~~~~~~~~~
make: *** [source/ProgArgs.o] Error 1
```

It looks like `#include <cuda_runtime.h>` is missing from that file (in v3.0.19), and indeed:

https://github.com/breuner/elbencho/blob/3244fe8bee1b93c30ecbf1e9521931c4d3e49445/source/ProgArgs.cpp#L23-L26

Looks like it's only included when `CUFILE_SUPPORT=1`.

When I move the `#include <cuda_runtime.h>` outside of the ifdef, compilation progresses further, until the final linking phase where I'm greeted with a _massive_ linker error (which I'm gonna hide behind a details tag).

<details><summary>Linker error</summary>

```
[...]
g++ -o ./bin/elbencho-unstripped ./source/HTTPService.o ./source/Logger.o ./source/toolkits/FileTk.o ./source/toolkits/SystemTk.o ./source/toolkits/TranslatorTk.o ./source/toolkits/S3Tk.o ./source/toolkits/UnitTk.o ./source/toolkits/OpsLogger.o ./source/toolkits/Base64Encoder.o ./source/toolkits/SignalTk.o ./source/toolkits/net/Socket.o ./source/toolkits/net/BasicSocket.o ./source/toolkits/HashTk.o ./source/toolkits/TerminalTk.o ./source/toolkits/random/RandAlgoSelectorTk.o ./source/toolkits/StringTk.o ./source/workers/WorkerManager.o ./source/workers/WorkersSharedData.o ./source/workers/LocalWorker.o ./source/workers/Worker.o ./source/workers/RemoteWorker.o ./source/S3UploadStore.o ./source/ProgArgs.o ./source/Main.o ./source/CPUUtil.o ./source/HTTPServiceUWS.o ./source/LatencyHistogram.o ./source/PathStore.o ./source/HTTPServiceSWS.o ./source/Statistics.o ./source/Coordinator.o -rdynamic -pthread -l rt -l stdc++fs -lnuma -laio -lboost_program_options -lboost_system -lboost_thread -O3  -lncurses -lcudart -lcurand -ldl 
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `ProgArgs::printHelpBlockDev()':
/home/ajaam/src/elbencho-3.0-19/source/ProgArgs.cpp:2608:(.text+0x792c): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/software/binutils/2.41.90/bin/ld: /home/ajaam/src/elbencho-3.0-19/source/ProgArgs.cpp:2626:(.text+0x7a6a): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/software/binutils/2.41.90/bin/ld: /home/ajaam/src/elbencho-3.0-19/source/ProgArgs.cpp:2648:(.text+0x7bc0): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `ProgArgs::printHelpMultiFile()':
/home/ajaam/src/elbencho-3.0-19/source/ProgArgs.cpp:2702:(.text+0x807c): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/software/binutils/2.41.90/bin/ld: /home/ajaam/src/elbencho-3.0-19/source/ProgArgs.cpp:2737:(.text+0x8292): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:/home/ajaam/src/elbencho-3.0-19/source/ProgArgs.cpp:2753: more undefined references to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)' follow
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `boost::program_options::variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/usr/include/boost/program_options/variables_map.hpp:155:(.text+0x111d1): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/software/binutils/2.41.90/bin/ld: /usr/include/boost/program_options/variables_map.hpp:155:(.text+0x116f5): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `ProgArgs::ProgArgs(int, char**)':
/home/ajaam/src/elbencho-3.0-19/source/ProgArgs.cpp:68:(.text+0x11e0b): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
/usr/include/boost/program_options/detail/value_semantic.hpp:170:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE6xparseERNS_3anyERKSt6vectorIS7_SaIS7_EE[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE6xparseERNS_3anyERKSt6vectorIS7_SaIS7_EE]+0x19): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `boost::program_options::typed_value<unsigned long, char>::name[abi:cxx11]() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19:(.text._ZNK5boost15program_options11typed_valueImcE4nameB5cxx11Ev[_ZNK5boost15program_options11typed_valueImcE4nameB5cxx11Ev]+0x1e): undefined reference to `boost::program_options::arg[abi:cxx11]'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `boost::program_options::typed_value<unsigned short, char>::name[abi:cxx11]() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19:(.text._ZNK5boost15program_options11typed_valueItcE4nameB5cxx11Ev[_ZNK5boost15program_options11typed_valueItcE4nameB5cxx11Ev]+0x1e): undefined reference to `boost::program_options::arg[abi:cxx11]'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `boost::program_options::typed_value<int, char>::name[abi:cxx11]() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19:(.text._ZNK5boost15program_options11typed_valueIicE4nameB5cxx11Ev[_ZNK5boost15program_options11typed_valueIicE4nameB5cxx11Ev]+0x1e): undefined reference to `boost::program_options::arg[abi:cxx11]'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char>::name() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19:(.text._ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE4nameEv[_ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE4nameEv]+0x1e): undefined reference to `boost::program_options::arg[abi:cxx11]'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name() const':
/usr/include/boost/program_options/detail/value_semantic.hpp:19:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameEv[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameEv]+0x1e): undefined reference to `boost::program_options::arg[abi:cxx11]'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:/usr/include/boost/program_options/detail/value_semantic.hpp:19: more undefined references to `boost::program_options::arg[abi:cxx11]' follow
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > boost::program_options::to_internal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/usr/include/boost/program_options/detail/convert.hpp:79:(.text._ZN5boost15program_options25basic_command_line_parserIcEC2EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC5EiPKPKc]+0x125): undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
/usr/include/boost/program_options/detail/parsers.hpp:43:(.text._ZN5boost15program_options25basic_command_line_parserIcEC2EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC5EiPKPKc]+0x166): undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int)':
/usr/include/boost/program_options/detail/value_semantic.hpp:149:(.text._ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi.isra.0[_ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE6xparseERNS_3anyERKSA_]+0xb3): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/software/binutils/2.41.90/bin/ld: /usr/include/boost/program_options/detail/value_semantic.hpp:153:(.text._ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi.isra.0[_ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE6xparseERNS_3anyERKSA_]+0x385): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/usr/include/boost/program_options/errors.hpp:372:(.text._ZN5boost15program_options10validators17get_single_stringIcEERKNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEERKSt6vectorIS9_SaIS9_EEb[_ZN5boost15program_options10validators17get_single_stringIcEERKNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEERKSt6vectorIS9_SaIS9_EEb]+0x90): undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
/software/binutils/2.41.90/bin/ld: /usr/include/boost/program_options/errors.hpp:372:(.text._ZN5boost15program_options10validators17get_single_stringIcEERKNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEERKSt6vectorIS9_SaIS9_EEb[_ZN5boost15program_options10validators17get_single_stringIcEERKNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEERKSt6vectorIS9_SaIS9_EEb]+0xa4): undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/software/binutils/2.41.90/bin/ld: /usr/include/boost/program_options/errors.hpp:372:(.text._ZN5boost15program_options10validators17get_single_stringIcEERKNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEERKSt6vectorIS9_SaIS9_EEb[_ZN5boost15program_options10validators17get_single_stringIcEERKNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEERKSt6vectorIS9_SaIS9_EEb]+0x170): undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
/software/binutils/2.41.90/bin/ld: /usr/include/boost/program_options/errors.hpp:372:(.text._ZN5boost15program_options10validators17get_single_stringIcEERKNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEERKSt6vectorIS9_SaIS9_EEb[_ZN5boost15program_options10validators17get_single_stringIcEERKNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEERKSt6vectorIS9_SaIS9_EEb]+0x184): undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `void boost::program_options::validate<unsigned long, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned long*, long)':
/usr/include/boost/program_options/detail/value_semantic.hpp:92:(.text._ZN5boost15program_options8validateImcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l.isra.0[_ZNK5boost15program_options11typed_valueImcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE]+0x149): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `void boost::program_options::validate<unsigned short, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned short*, long)':
/usr/include/boost/program_options/detail/value_semantic.hpp:92:(.text._ZN5boost15program_options8validateItcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l.isra.0[_ZNK5boost15program_options11typed_valueItcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE]+0x451): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `void boost::program_options::validate<long, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, long*, long)':
/usr/include/boost/program_options/detail/value_semantic.hpp:92:(.text._ZN5boost15program_options8validateIlcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l.isra.0[_ZNK5boost15program_options11typed_valueIlcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE]+0x182): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `void boost::program_options::validate<int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long)':
/usr/include/boost/program_options/detail/value_semantic.hpp:92:(.text._ZN5boost15program_options8validateIicEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l.isra.0[_ZNK5boost15program_options11typed_valueIicE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE]+0x182): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o: in function `void boost::program_options::validate<unsigned int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int*, long)':
/usr/include/boost/program_options/detail/value_semantic.hpp:92:(.text._ZN5boost15program_options8validateIjcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l.isra.0[_ZNK5boost15program_options11typed_valueIjcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE]+0x149): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): more undefined references to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcEE[_ZTVN5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE[_ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost15program_options11typed_valueIjcEE[_ZTVN5boost15program_options11typed_valueIjcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost15program_options11typed_valueImcEE[_ZTVN5boost15program_options11typed_valueImcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost15program_options11typed_valueItcEE[_ZTVN5boost15program_options11typed_valueItcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/software/binutils/2.41.90/bin/ld: ./source/ProgArgs.o:(.rodata._ZTVN5boost15program_options11typed_valueIicEE[_ZTVN5boost15program_options11typed_valueIicEE]+0x38): more undefined references to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const' follow
collect2: error: ld returned 1 exit status
make: *** [bin/elbencho-unstripped] Error 1
```

</details>

I'm not fluent in C++. Any idea what I can do about this error...?

**Comment by breuner** [comment]
Hi @runiq ,

nice catch regarding the missing include. It's exactly like you wrote and I've made a corresponding update in the master branch here on Github and thanked you in the changelog.

The other problem that you encountered is unfortunately quite mysterious... 

You probably are aware already, but just to be sure: If you don't need GPU support on these hosts and if it's not important to you to compile from source, then you could just take the pre-compliled static binary from the releases section here: https://github.com/breuner/elbencho/releases

In the error messages, the linker is complaining that it's missing `boost::program_options::options_description::options_description` and other functions from the boost_program_options library. This is strange because the boost library header files seem to contain these functions, otherwise the compiler would have complained earlier with the "was not declared" messages, similar to the ones that you saw for the missing include. And you also seem to have the corresponding boost_program_options.so library on your system, because otherwise the linker would complain that it can't find the library for the `-l boost_program_options` that we correctly see as parameter in your `g++` command line.

So the library is there, but somehow doesn't seem to match what is found in the header files.

Is it possible that the boost_program_options.so library version does not match the version of the program_options.hpp header file on your system? (E.g. is there maybe a custom installation of the boost.org libraries on this host and the include files are taken from this custom path but the `.so` library gets linked from the path of the boost library that came with RHEL7 or vice versa?)

Maybe not really helpful in this context, but at least for the sake of completeness: This is the RHEL/CentOS 7 Dockerfile: https://github.com/breuner/elbencho/blob/master/build_helpers/docker/Dockerfile.centos7
The first `RUN` section shows the build steps on the latest available official CentOS 7.9 docker container. This runs automatically for every new change in the master branch and builds successfully with the current version, so it seems like there is at least no general problem with RHEL/CentOS 7, so must be something "special" in your case.

**Comment by runiq** [comment]
Hi, thanks for the quick reply, and I'm sorry for _my_ long delay in replying -- we had a massive cluster outage and then I got sick.

Thanks for your insight regarding the linker error! I thought a new version of boost would help, but even with very recent versions of Boost (1.86.0), binutils (2.41.90, for the linker), GCC (13.2), and OpenMPI (5.0), I'm still seeing the same error. I'll see if I can find anything else.

> You probably are aware already, but just to be sure: If you don't need GPU support on these hosts and if it's not important to you to compile from source, then you could just take the pre-compliled static binary from the releases section here:

Yeah, I probably should state the reason why I'm building from source in the first place. I want to include elbencho in the list of required benchmarks for the procurement of our new cluster, and for that I need an example output with the right compilation options. Unfortunately I don't have any newer machine with GDS- or even CUDA-capable CPUs available. (This is why we're doing a new procurement in the first place. :) )

Somewhat off topic, but is there even any point in me requiring CUDA support without GDS? What I mean is, is there any functionality from CUDA that can improve the benchmark results?

**Comment by runiq** [comment]
> Here is an easy way to verify at least which paths are being used for the include file and for the library... (at least I hope that it works to also print these paths in your case before gcc errors out) :
>
> First we create a mini C++ program that includes the boost program options header and calls some function from the program options package:
>
> ```
> breuner@node001:/tmp$ echo -e "#include <boost/program_options.hpp>\nint main( {boost::program_options::options_description desc(\"test\"); return 0;}" > test.cpp
> ```
>
> Now we can call g++ with special options to print the path that it's using for the .hpp include file and the .so shared library file. In my case, both are the system defaults (on the Ubuntu 24.04 system that I'm using for this test):
>
> ```
> breuner@node001:/tmp$ g++ -H test.cpp -o test -Wl,-t -l boost_program_options 2>&1 | grep -e program_options.so -e program_options.hpp
>
> . /usr/include/boost/program_options.hpp
> /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/libboost_program_options.so
> ```

That little program actually reproduces the error, and it seems that indeed I'm mixing up my custom installed version of boost and the system version! Thanks a lot for that neat little trick, that's definitely going into my toolbox! <3

I believe that you've put me on the right path with this. Our cluster messes with `LD_LIBRARY_PATH` and `CPATH` via Lmod/environment-modules, which is probably where I messed something up. I'll close this because it seems to be a 'me' problem.

You've gone above and beyond in helping me with this. I can't overstate how helpful your comments have been, not only with this issue in particular, but with other linking problems that I definitely _will_ encounter in the future. :) Take care!

**Comment by runiq** [comment]
Final comment for closure: Boost installs its libraries into a `/path/to/boost/lib` directory, but adding that directory to `LIBRARY_PATH` results in the following addition to GCC's linker's library search path: `/path/to/boost/lib/../lib64`. In the end, adding a `lib64` symlink next to the `lib` directory was all that was necessary.

**Comment by breuner** [comment]
Thank you, @runiq !
